package com.wdmmg.expense.mail.inbound.resend;

import com.fasterxml.jackson.databind.JsonNode;
import com.wdmmg.expense.mail.inbound.EmailTextCleaner;
import com.wdmmg.expense.mail.inbound.ReceivedEmail;

import java.time.Instant;
import java.time.format.DateTimeParseException;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import java.util.TreeMap;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

/** Turns Resend's received-email JSON into the app's transport-neutral {@link ReceivedEmail}. */
final class ResendEmailMapper {
    private static final Pattern NAME_ADDR = Pattern.compile("^\\s*\"?([^\"<]*?)\"?\\s*<([^>]+)>\\s*$");

    private ResendEmailMapper() {}

    static ReceivedEmail map(JsonNode e) {
        Map<String, String> headers = headers(e.path("headers"));
        String from = text(e, "from");
        if (from == null) from = headers.get("from");
        String[] addr = parseAddress(from);

        String messageId = text(e, "message_id");
        if (messageId == null) messageId = headers.get("message-id");
        if (messageId == null) messageId = "<resend-" + text(e, "id") + "@resend>";

        List<String> to = new ArrayList<>();
        e.path("to").forEach(n -> to.add(n.asText()));

        Instant received;
        try {
            received = e.hasNonNull("created_at") ? Instant.parse(e.get("created_at").asText()) : Instant.now();
        } catch (DateTimeParseException ex) {
            received = Instant.now();
        }

        String body = EmailTextCleaner.clean(text(e, "text"), text(e, "html"));
        return new ReceivedEmail(messageId, addr[1], addr[0], String.join(", ", to), text(e, "subject"), body, received,
                authenticationResults(e.path("authentication"), headers), autoGenerated(headers));
    }

    /** "Name <a@b.c>" or "a@b.c" → {name|null, lower-cased address}. */
    static String[] parseAddress(String raw) {
        if (raw == null || raw.isBlank()) return new String[]{null, "unknown"};
        Matcher m = NAME_ADDR.matcher(raw);
        if (m.matches()) {
            String name = m.group(1).trim();
            return new String[]{name.isEmpty() ? null : name, m.group(2).trim().toLowerCase(Locale.ROOT)};
        }
        return new String[]{null, raw.trim().toLowerCase(Locale.ROOT)};
    }

    /**
     * Resend reports verdicts as {"spf":"pass","dkim":"pass","dmarc":"pass"}; render them like an
     * Authentication-Results header so the same sender checks apply to IMAP and Resend mail.
     */
    private static String authenticationResults(JsonNode auth, Map<String, String> headers) {
        if (auth != null && auth.isObject() && auth.size() > 0) {
            List<String> parts = new ArrayList<>();
            for (String k : List.of("spf", "dkim", "dmarc")) {
                if (auth.hasNonNull(k)) parts.add(k + "=" + auth.get(k).asText().toLowerCase(Locale.ROOT));
            }
            if (!parts.isEmpty()) return String.join("; ", parts);
        }
        return headers.get("authentication-results");
    }

    private static boolean autoGenerated(Map<String, String> h) {
        String autoSubmitted = h.get("auto-submitted");
        if (autoSubmitted != null && !autoSubmitted.trim().equalsIgnoreCase("no")) return true;
        String precedence = h.get("precedence");
        if (precedence != null && precedence.toLowerCase(Locale.ROOT).matches(".*(bulk|junk|list|auto_reply).*")) return true;
        return h.containsKey("list-id") || h.containsKey("x-autoreply") || h.containsKey("x-autorespond");
    }

    /** Case-insensitive; array values are joined. */
    private static Map<String, String> headers(JsonNode node) {
        Map<String, String> out = new TreeMap<>(String.CASE_INSENSITIVE_ORDER);
        if (node == null || !node.isObject()) return out;
        Iterator<Map.Entry<String, JsonNode>> it = node.fields();
        while (it.hasNext()) {
            Map.Entry<String, JsonNode> f = it.next();
            JsonNode v = f.getValue();
            if (v.isArray()) {
                List<String> vals = new ArrayList<>();
                v.forEach(x -> vals.add(x.asText()));
                out.put(f.getKey(), String.join("; ", vals));
            } else if (!v.isNull()) {
                out.put(f.getKey(), v.asText());
            }
        }
        return out;
    }

    private static String text(JsonNode n, String field) {
        JsonNode v = n.get(field);
        return v == null || v.isNull() || v.asText().isBlank() ? null : v.asText();
    }
}
