package com.wdmmg.expense.mail.inbound;

import jakarta.mail.Address;
import jakarta.mail.MessagingException;
import jakarta.mail.Multipart;
import jakarta.mail.Part;
import jakarta.mail.internet.InternetAddress;
import jakarta.mail.internet.MimeMessage;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.time.Instant;
import java.util.HexFormat;
import java.util.Locale;
import java.util.stream.Collectors;
import java.util.stream.Stream;

/** Converts a Jakarta Mail message into a transport-neutral {@link ReceivedEmail}. */
final class MimeMessageReader {
    private MimeMessageReader() {}

    static ReceivedEmail read(MimeMessage m) throws MessagingException, IOException {
        InternetAddress from = firstAddress(m.getFrom());
        String fromAddress = from == null ? "unknown" : from.getAddress().toLowerCase(Locale.ROOT);
        String fromName = from == null ? null : from.getPersonal();
        String to = m.getRecipients(jakarta.mail.Message.RecipientType.TO) == null ? null
                : Stream.of(m.getRecipients(jakarta.mail.Message.RecipientType.TO)).map(Address::toString).collect(Collectors.joining(", "));
        Instant received = m.getReceivedDate() != null ? m.getReceivedDate().toInstant()
                : m.getSentDate() != null ? m.getSentDate().toInstant() : Instant.now();
        String subject = m.getSubject();

        String messageId = m.getMessageID();
        if (messageId == null || messageId.isBlank()) {
            messageId = "<synthetic-" + sha256(fromAddress + "|" + received + "|" + subject) + "@local>";
        }

        Bodies bodies = new Bodies();
        collect(m, bodies);
        String text = EmailTextCleaner.clean(bodies.plain, bodies.html);

        return new ReceivedEmail(messageId, fromAddress, fromName, to, subject, text, received,
                header(m, "Authentication-Results"), isAutoGenerated(m));
    }

    private static final class Bodies {
        String plain;
        String html;
    }

    /** First text/plain and first text/html that aren't attachments, searching nested multiparts. */
    private static void collect(Part part, Bodies out) throws MessagingException, IOException {
        if (Part.ATTACHMENT.equalsIgnoreCase(part.getDisposition())) return;
        if (part.isMimeType("text/plain") && out.plain == null) {
            out.plain = asString(part.getContent());
        } else if (part.isMimeType("text/html") && out.html == null) {
            out.html = asString(part.getContent());
        } else if (part.isMimeType("multipart/*")) {
            Multipart mp = (Multipart) part.getContent();
            for (int i = 0; i < mp.getCount(); i++) collect(mp.getBodyPart(i), out);
        }
    }

    private static String asString(Object content) throws IOException {
        if (content instanceof String s) return s;
        if (content instanceof java.io.InputStream in) return new String(in.readAllBytes(), StandardCharsets.UTF_8);
        return null;
    }

    private static boolean isAutoGenerated(MimeMessage m) throws MessagingException {
        String autoSubmitted = header(m, "Auto-Submitted");
        if (autoSubmitted != null && !autoSubmitted.trim().equalsIgnoreCase("no")) return true;
        String precedence = header(m, "Precedence");
        if (precedence != null && precedence.toLowerCase(Locale.ROOT).matches(".*(bulk|junk|list|auto_reply).*")) return true;
        return header(m, "List-Id") != null || header(m, "X-Autoreply") != null || header(m, "X-Autorespond") != null;
    }

    private static String header(MimeMessage m, String name) throws MessagingException {
        String[] values = m.getHeader(name);
        return values == null || values.length == 0 ? null : String.join("; ", values);
    }

    private static InternetAddress firstAddress(Address[] addresses) {
        if (addresses == null) return null;
        for (Address a : addresses) if (a instanceof InternetAddress ia) return ia;
        return null;
    }

    private static String sha256(String s) {
        try {
            return HexFormat.of().formatHex(MessageDigest.getInstance("SHA-256").digest(s.getBytes(StandardCharsets.UTF_8))).substring(0, 32);
        } catch (NoSuchAlgorithmException e) {
            throw new IllegalStateException(e);
        }
    }
}
