package com.wdmmg.expense.mail.inbound;

import java.time.Instant;

/**
 * A message as it arrived, independent of how it was fetched (IMAP today; a provider
 * webhook or the admin "simulate" endpoint work the same way).
 *
 * @param text                  readable body: plain text, quoted replies and signature removed
 * @param authenticationResults the receiving server's SPF/DKIM/DMARC verdicts, if present
 * @param autoGenerated         bounce, out-of-office, mailing list … – never acted on
 */
public record ReceivedEmail(String messageId, String fromAddress, String fromName, String to, String subject,
                            String text, Instant receivedAt, String authenticationResults, boolean autoGenerated) {}
