package com.wdmmg.expense.mail.inbound;

import java.util.Locale;
import java.util.regex.Pattern;

/** Cheap guards applied to every inbound message before any handler sees it. */
final class SenderChecks {
    private static final Pattern NO_REPLY = Pattern.compile("^(mailer-daemon|postmaster|no-?reply|do-?not-?reply)@", Pattern.CASE_INSENSITIVE);

    private SenderChecks() {}

    static boolean looksAutomated(ReceivedEmail e) {
        return e.autoGenerated() || NO_REPLY.matcher(e.fromAddress()).find();
    }

    /**
     * Uses the verdicts the receiving server (e.g. Gmail) recorded in Authentication-Results.
     * No header → can't judge, allow. DMARC fail → reject. Otherwise SPF or DKIM must pass.
     * This is what stops someone forging a user's From: address to add expenses for them.
     */
    static boolean senderAuthenticated(String authenticationResults) {
        if (authenticationResults == null || authenticationResults.isBlank()) return true;
        String h = authenticationResults.toLowerCase(Locale.ROOT);
        if (h.contains("dmarc=fail")) return false;
        return h.contains("spf=pass") || h.contains("dkim=pass");
    }
}
