package com.tahir.finance.expense.domain;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import lombok.Getter;
import lombok.Setter;

import java.time.Instant;
import java.util.UUID;

@Entity
@Table(name = "expenses")
@Getter
@Setter
public class Expense {

    @Id
    private UUID id;

    @Column(name = "user_id", nullable = false)
    private UUID userId;

    /** Minor units - paise for INR. Never a floating point type. */
    @Column(name = "amount_minor", nullable = false)
    private long amountMinor;

    @Column(name = "currency_code", nullable = false, length = 3)
    private String currencyCode;

    @Column(name = "spent_at", nullable = false)
    private Instant spentAt;

    @Column(name = "category_id")
    private UUID categoryId;

    @Column(name = "trip_id")
    private UUID tripId;

    private String merchant;

    private String note;

    @Column(name = "payment_method")
    @Enumerated(EnumType.STRING)
    private PaymentMethod paymentMethod;

    @Column(nullable = false)
    @Enumerated(EnumType.STRING)
    private ExpenseOrigin origin = ExpenseOrigin.MANUAL;

    @Column(name = "source_occurrence_id")
    private UUID sourceOccurrenceId;

    @Column(name = "source_split_id")
    private UUID sourceSplitId;

    @Column(nullable = false)
    @Enumerated(EnumType.STRING)
    private ReimbursementState reimbursement = ReimbursementState.NOT_APPLICABLE;

    @Column(name = "idempotency_key")
    private String idempotencyKey;

    @Column(name = "created_at", nullable = false)
    private Instant createdAt = Instant.now();

    @Column(name = "updated_at", nullable = false)
    private Instant updatedAt = Instant.now();

    @Column(name = "deleted_at")
    private Instant deletedAt;

    /**
     * Rows mirrored from a group expense or generated by autopay are owned by
     * the module that produced them. Editing them directly would let the two
     * ledgers drift apart.
     */
    public boolean isDerived() {
        return origin != ExpenseOrigin.MANUAL;
    }
}
