package com.tahir.finance.expense.domain;

public enum ExpenseOrigin {
    /** Entered by the user. */
    MANUAL,
    /** Generated by the scheduler from a recurring payment. */
    AUTOPAY,
    /** Mirrored from one member's share of a group expense. */
    GROUP
}
